LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

ENTITY TTOVECT IS
PORT(
	A : IN STD_LOGIC;
	B : IN STD_LOGIC;
	C : IN STD_LOGIC;

	S : OUT STD_LOGIC_VECTOR(0 TO 2)
);
END TTOVECT;

ARCHITECTURE BEHAVORIAL OF TTOVECT IS
	BEGIN
		S(2)<=A;
		S(1)<=B;
		S(0)<=C;
END BEHAVORIAL;